morena/app.py
#Starter app for a daycare
from flask import Flask

from morena.blueprints.page import page

def create_app():
    """Make a factory pattern"""

    app= Flask(__name__,instance_relative_config=True)
    app.config.from_object('config.settings')
    app.config.from_pyfile('settings.py',silent=True)

    app.register_blueprint(page)

    return app

morena/blueprints/page/__init__.py
from morena.blueprints.page.views import page

morena/blueprints/page/views.py
#In here we have our routes for our webpage

from flask import Blueprint, render_template

page = Blueprint('page', __name__,template_folder='templates')

@page.route('/')
def home():
    return render_template('page/home.html')

@page.route('/terms')
def terms():
    return render_template('page/terms.html')

@page.route('/policy')
def policy():
    return render_template('page/policy.html')

@page.route('/about')
def about():
    return render_template('page/about.html')

morena/templates/layouts/base_test.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Morena's Daycare</title>

  <!-- Bootstrap core CSS -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/static/css/modern-business.css" rel="stylesheet">

</head>
<body>
  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-success fixed-top">
    <div class="container">
        <a href="{{ url_for('page.home') }}">
            <img src="{{ url_for('static', filename='images/real-morenas-daycare_02.png') }}"
                 class="rounded-circle"
                 width="117" height="95" title="Morena's Daycare" alt="Morena's Daycare"/>
        </a>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('page.about')}}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">Contact</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Portfolio
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="">1 Column Portfolio</a>
              <a class="dropdown-item" href="">2 Column Portfolio</a>
              <a class="dropdown-item" href="">3 Column Portfolio</a>
              <a class="dropdown-item" href="">4 Column Portfolio</a>
              <a class="dropdown-item" href="">Single Portfolio Item</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Blog
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
              <a class="dropdown-item" href="">Blog Home 1</a>
              <a class="dropdown-item" href="">Blog Home 2</a>
              <a class="dropdown-item" href="">Blog Post</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Other Pages
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
              <a class="dropdown-item" href="">Full Width Page</a>
              <a class="dropdown-item" href="">Sidebar Page</a>
              <a class="dropdown-item" href="">FAQ</a>
              <a class="dropdown-item" href="">404</a>
              <a class="dropdown-item" href="">Pricing Table</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% block body %}{% endblock %}
  <!-- Footer -->
  <footer class="page-footer fixed-bottom bg-success">
    <div class="container">
      <ul class="list-inline">
        <li class="text-muted text-center"> Morena's Daycare &copy; 2020</li>
      </ul>
    </div>
  </footer>
  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>